name: Integrationtest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile -t container-manager

      - name: Build the Docker image (Integrationtest)
        run: docker build . --file ./test/integrationtest/Dockerfile -t integrationtest

      - name: Create a local storage directory
        run: mkdir ./storage && sudo chown 500:500 -R ./storage && ls -la ./storage

      - name: Run the integrationtest container
        run: docker run -p 8080:8080 -v storage:/storage integrationtest:latest

      - name: Test the integrationtest app
        run: curl -v localhost:8080 2>/dev/null | head -n 1 | cut -d$' ' -f2 | grep 200

      - name: Restart the integrationtest app
        run: docker exec -it $(docker ps --filter "ancestor=integrationtest:latest" --format "{{.ID}}") supervisorctl -c /image/supervisor/global.conf -s unix:///tmp/supervisord.sock restart app

      - name: Test the integrationtest app (again)
        run: curl localhost:8080 2>/dev/null | head -n 1 | cut -d$' ' -f2 | grep 200